### ISSUE TITLE
Dynamic "visible" and "required" (or: evaluate expressions rather than hardcoded boolean)

### ISSUE THREAD

**Issue by simendsjo** [Altinn/app-template-dotnet#45] opened 2022-03-02 08:13 UTC
In questionnaire design, it's very common for fields like visible and required
to be calculated based on data in the questionnaire. Because of this, tools use
a DSL rather than hardcoded values. This language usually include common things
like symbols (data field), bools, numbers, strings, sets, maps, lists, and
operations on them.

Let's give an example to show a common and simple use-case, which seems very difficult
to implement in Altinn3 today.

We have a question for additional information, and when 'Yes', two extra fields
should be visible and required. When pressing 'No', they should not be visible
nor required, and the data entered (in case we chose 'Yes' and later 'No')
should not be stored/filed (as it doesn't "exist"). When going from 'No' to 'Yes',
previous entered data should be visible, ie. the fields shouldn't be cleared
unless done so explicitly.

```
additional-data [ ] Yes / [ ] No
  Field1 [       ]
  Field2 [       ]
```

In pseudocode we then have
```json
{
    "id": "additional-data",
    "visible": "true",
    "required": "true"
},
{
    "id": "field1",
    "visible": "additional-data = 'Yes'",
    "required": "additional-data = 'Yes'",
    "filed": "additional-data = 'Yes'"
},
{
    "id": "field2",
    "visible": "additional-data = 'Yes'",
    "required": "additional-data = 'Yes'",
    "filed": "additional-data = 'Yes'"
}
```

I've tried to find workarounds to reuse existing "required" logic, but I've been
unable to find something which works. I cannot find a way to change the
FormLayout, and changes done to the datamodel doesn't seem to be reflected
anywhere and is reverted when the method exists.

Implementing a simple DSL like this isn't very difficult, but it's more stuff to
maintain, especially since it's best to support the language both backend and
frontend. Using something existing like an embeddable scheme might be a good
solution over a custom DSL as we can piggy-back on existing libraries.

**Comment by simendsjo** [comment] 2022-03-04 09:45
With the help of Terje Holene, I managed to get something working, but adding this simple "conditional data field" requires lots of manual changes even for a trivial application. Let's show the changes (I'll ignore setup of additional services in ctor/fields).
This is a very common pattern, and exists in plenty of apps/forms. The workaround is tedious, error-prone, requires knowledge of internal stringly typed data, and doesn't give the same UX.
As stated, other solutions solves this using expressions rather than hardcoded values, which doesn't require any additional code.

All the things below could be solved by something like
```json
"visible": "paa-vegne-av = 'Ja'",
"required": "paa-vegne-av = 'Ja'",
"export-to-pdf": "paa-vegne-av = 'Ja'"
"store-data": "paa-vegne-av = 'Ja'"
```

or even

```json
"visible": "true",
"required": "true",
"exists": "paa-vegne-av = 'Ja'"
```

# Dynamic visible

## RuleHandler.js

```javascript
var conditionalRuleHandlerObject = {
  paaVegneAvAndre: function(obj) {
    return obj && obj.value && obj.value === "Ja";
  },
}

var conditionalRuleHandlerHelper = {
  paaVegneAvAndre: function() {
    return {
      value: "value"
    }
  }
}

```

## RuleConfiguration.json

```json
{
  "data": {
    "ruleConnection": {},
    "conditionalRendering": {
      "paa-vegne-av": {
        "selectedFunction": "paaVegneAvAndre",
        "selectedAction": "Show",
        "inputParams": {
          "value": "RapportKRT-1127.soeknadPaaVegneAv.paavegneav.value"
        },
        "selectedFields": {
          "navn": "paa-vegne-av-navn",
          "organisasjonsnummer": "paa-vegne-av-organisasjonsnummer"
        }
      }
    }
  }
}
```

## FormatPdf

```csharp
public async Task<LayoutSettings> FormatPdf(LayoutSettings layoutSettings, object data)
{
    var model = (KRT1127SoeknadsskjemaForKapitalforhoeyelserOgNedsettelserIForsikringsforetak_M) data;
    if (model.RapportKRT1127.soeknadPaaVegneAv.paavegneav.value == "Nei")
    {
        layoutSettings.Components.ExcludeFromPdf.Add("paa-vegne-av-organisasjonsnummer");
        layoutSettings.Components.ExcludeFromPdf.Add("paa-vegne-av-navn");
    }
    return await Task.FromResult(layoutSettings);
}
```

# Conditional required

## Validation
While this at least shows a message, it doesn't give the same UX as a required setting on the field.

```csharp
public async Task ValidateData(object data, ModelStateDictionary validationResults)
{
    var model = (KRT1127SoeknadsskjemaForKapitalforhoeyelserOgNedsettelserIForsikringsforetak_M) data;
    if (model.RapportKRT1127.soeknadPaaVegneAv.paavegneav.value == "Ja")
    {
        if (string.IsNullOrWhiteSpace(model.RapportKRT1127.soeknadPaaVegneAv.organisjonsnummer?.value))
        {
            validationResults.AddModelError("paa-vegne-av-organisasjonsnummer", "paa-vegne-av-organisasjonsnummer-required");
        }
        if (string.IsNullOrWhiteSpace(model.RapportKRT1127.soeknadPaaVegneAv.organisasjonsnavn?.value))
        {
            validationResults.AddModelError("paa-vegne-av-navn", "paa-vegne-av-navn-required");
        }
    }

    await Task.CompletedTask;
}
```

## Removing wrong data

When the field is "Nei", the data haven't been filed, and we need to delete it in case it was temporarily filed to avoid knowledge of this erronous data in later steps.

```csharp
public override async Task RunProcessTaskEnd(string taskId, Instance instance)
{
    var ty = typeof(KRT1127SoeknadsskjemaForKapitalforhoeyelserOgNedsettelserIForsikringsforetak_M);
    string app = instance.AppId.Split("/")[1];
    string org = instance.Org;
    Guid instanceGuid = Guid.Parse(instance.Id.Split("/")[1]);
    var dataElement = instance.Data.Single();
    int instanceOwnerId = int.Parse(instance.InstanceOwner.PartyId);
    var dataId = new Guid(dataElement.Id);

    var data = (KRT1127SoeknadsskjemaForKapitalforhoeyelserOgNedsettelserIForsikringsforetak_M) await _dataService.GetFormData(instanceGuid, ty, org, app, instanceOwnerId, dataId);
    if (data.RapportKRT1127.soeknadPaaVegneAv.paavegneav.value == "Nei")
    {
        data.RapportKRT1127.soeknadPaaVegneAv.organisjonsnummer = null;
        data.RapportKRT1127.soeknadPaaVegneAv.organisasjonsnavn = null;
        await _dataService.UpdateData(data, instanceGuid, ty, org, app, instanceOwnerId, dataId);
    }
}
```

**Comment by olemartinorg** [comment] 2022-11-15 10:34
Closing as duplicate of:
- Altinn/app-lib-dotnet/issues/9
- Altinn/app-frontend-react/issues/355

The work behind this issue was instrumental in finding a solution - thank you for the contribution! :partying_face:

**Closed by olemartinorg** 2022-11-15 10:34 UTC
Labels: org/krt
